### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by fivge** [fivge/mockjs#1]
todos

方向 1

> 工具链: 开发、构建优化, CI/CD 完善的支持

-   [ ] #2
-   [ ] swc to dev/build
-   [ ] vitest to test

方向 2

> 代码: 代码逻辑优化, 功能增加

-   [ ] merge some fixs in issues

方向 3

> 使用体验提升: typescript 类型支持

方向 4

> 其他运行时支持: 如 demo、bun、cloudflare worker

方向 5

> 文档完善: demo 页面, doc 目录

-   [ ] demo site in code
-   [ ] doc in code not wiki
